FROM python:3.11-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:0.5.0 /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock README.md ./
COPY src/ ./src/

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy
RUN uv sync --extra ui --no-dev --frozen

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8501

CMD ["streamlit", "run", "src/fraud_detection/ui/app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]